### ISSUE TITLE
Bold font

### ISSUE THREAD

**Issue by simon0356** [wezm/profont#13]
Hi,

I'd love to get this font in bold,  I understand i will need to generate specific bold version .raw and .xcf to generate the following .png 
How do I generate the bold version of the .raw and .xcf ? 

Thanks

**Comment by wezm** [comment]
Unfortunately the original font that this is derived from does not have a bold version:

>  By the way, ProFont doesn't contain a bold or an italic style, there’s regular only.

— https://tobiasjung.name/profont/

Some people have constructed a (vector) TrueType font (linked on the above page) in the ProFont style but because it's not hand crafted bitmaps like the regular weight it difficult to convert them and unlikely to look good. My recommendation would be to use different weights like the page above does to obtain bold-like emphasis. Do note that the larger sizes have a heavier stroke than the smaller ones, which gives them a bolder appearance.
